### ISSUE TITLE
Nx Console Roadmap

### ISSUE THREAD

**Issue by MaxKless** [nrwl/nx-console#1578]
## Hey everyone! 
We're excited to announce the release of **Nx Console for JetBrains IDEs** 🚀🚀
If you've been hanging around on here, this will probably not come as a surprise to you, because we've been working hard to get this out all year. 
You can find [Nx Console on the JetBrains Marketplace](https://plugins.jetbrains.com/plugin/21060-nx-console).

## Whats next?
After shipping the nxls and generate UI, we're already at work porting more features from VSCode and the community plugins. Big shoutout to @iguissouma who's been helping us out a lot and been super productive!

This issue is an attempt to make our work a little more transparent and involve the community - you, reading this right now - in this journey. We're hoping to provide the same integration and dev experience regardless of your choice of IDE.
So **please comment what you'd like to see in the upcoming versions of Nx Console and join the discussion.** 

Here's what we have planned so far: 
- [x] running move & remove generators via a native UI - ready for the next release! 🎉 
- [x] running generators & targets from the `Run Anything` menu - ready for the next release! 🎉 
- [x] add the project & task graph to IntelliJ - this is a super useful feature to reduce context switching
- [x] add gutters to `project.json` to quickly run targets - @iguissouma has already started working on this
- [x] more settings and context-aware actions to smoothly integrate into your workflows

In addition, there's a bunch of things we could port over, like
- the project view from VSCode - quickly get an overview of your workspace and run targets
- nx cloud integration
- run targets view from VSCode - quickly run any target from a toolwindow
- apps and libs icons in project view - thanks @Den-dp 
- generator running visualization - thanks @Den-dp 
- nxls startup/live state in the bottom toolbar
- ...? 

### This is where you come in! 
Let us know what features you'd like to see implemented - big or small, existing or new. 

Thanks for using Nx Console!  🤖🧑‍💻

**Comment by Den-dp** [comment]
That's awesome to see such collaboration with community plugin authors, and awesome that JetBrains IDEs became a first-class citizen for Nx Console.

Actually, your planned features look great to me!

But also I wanted to see the following features (that I liked about @iguissouma plugin):
* special icons for apps and libs (helps the eye navigate the folder structure)
![image](https://user-images.githubusercontent.com/1770529/222549771-cff0a71d-afb3-45a1-91c4-f21608e3d9ba.png)
* add visualization of the running generator (sometimes they take some time)
![image](https://user-images.githubusercontent.com/1770529/222549068-5074acc9-7a92-450a-8f86-7df9b7804a92.png)
* add run/debug widget
![image](https://user-images.githubusercontent.com/1770529/222552156-a79ccd96-c3d2-4440-8941-bfae1c5c6251.png)
* prefill projectname for `move` and `remove` refactoring actions (if calling from a folder context menu)

Thanks for your work folks 👍

**Comment by itspers** [comment]
Can you maybe publish more detailed existing features list? Cause its unclear how to understand if something is not implemented yet or bug. For example generators UI ignores all defaults from nx.json - is it just not done, or should work? 

@iguissouma please up old plugin's version dependencies so it can work with EAP 🙏

**Comment by MaxKless** [comment]
Hey @itspers the `nx.json` defaults should be picked up in the generate ui! Could you create a separate issue with a reproduction and details about your environment? Then we can have a look.

**Comment by jcassee** [comment]
Very cool to see support for IntelliJ/WebStorm! What would be very useful for me is supporting debugging an app. (Currently, it seems only running an app is supported.)

**Comment by MaxKless** [comment]
Yeah this is not the first time we've heard a request for debug support! Sounds like a good idea for a future release.

**Comment by localpcguy** [comment]
One thing I was just running into today is that in IntelliJ with the Angular plugin installed, there is an option in the Context->Refactor menu to "extract Angular component" for the selected/highlighted markup. Or in the main menu, under Refactor -> (either) Refactor This or Extract/Introduce -> Extract Component. Regardless of which one is selected, they all fail with the message "Required package @angular/cli not installed". The @angular/cli package is installed however. I'm open to this being a problem with the Angular plugin, except it worked when not using Nx. I'm not sure if the solution is to resolve the issue (or at least enter a bug for them to resolve), or if it is simply to add the ability in Nx Console to generate a component from a template snippet as well.

![image](https://user-images.githubusercontent.com/593240/230200102-f74f5d82-9dd1-4c8c-af8f-6fdb39c6eebd.png)

**Comment by MaxKless** [comment]
Since we've achieved feature-parity between VSCode extension and IntelliJ plugin, I'm closing this issue for now. 

If you have any more suggestions, please let us know and submit a feature request!
